title: Samuel Adeolu Olusegun
logo: /assests/img/Samuel-Olusegun.jpg
description: Highly skilled and experienced Data Analyst with expertise in SQL, Data Analysis, Data Visualization, and Data 
Storytelling. Proficient in Excel, Power BI, Tableau, R, Python, and Machine Learning. Passionate about transforming data into 
valuable insights to drive informed decision-making. Proven ability to conduct in-depth data analysis and create 
meaningful visualizations. Strong communication skills and a talent for simplifying complex concepts. Seeking 
a challenging position to contribute data analysis expertise and help organizations make data-driven decisions.
#show-downloads: true
theme: jekyll-theme-minimal
