title: Samuel Adeolu Olusegun
logo: /assests/img/Samuel-Olusegun.jpg
description: Data Professional, proficient in Excel, SQL, Power BI, Tableau, R, Python, and Machine Learning.
#show-downloads: true
theme: jekyll-theme-minimal

